// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18444
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Car.Com.Tests.Smoke.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("SmokeTest")]
    public partial class SmokeTestFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "SmokeTest.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "SmokeTest", "In order to ensure the website is working\r\nAs a tester\r\nI want to navigate throug" +
                    "h different scenarios to prove the website is working", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Research by Make")]
        [NUnit.Framework.CategoryAttribute("PRSubmission")]
        [NUnit.Framework.CategoryAttribute("Research")]
        [NUnit.Framework.CategoryAttribute("ByMake")]
        [NUnit.Framework.TestCaseAttribute("Ford", "Fusion", "js-disablesupertrim-fusionhybrids", "2015", "js-trimrow-35303", "fusion-hybrid-s", "overlayjs-trimcollection-fusionhybrids", null)]
        [NUnit.Framework.TestCaseAttribute("Honda", "Accord", "js-disablesupertrim-accordhybridbase", "2015", "js-trimrow-35764", "hybrid-base", "overlayjs-trimcollection-accordhybridbase", null)]
        [NUnit.Framework.TestCaseAttribute("Toyota", "Venza", "js-disablesupertrim-venzaxle", "2015", "js-trimrow-36780", "venza-xle-v6-awd", "overlayjs-trimcollection-venzaxle", null)]
        public virtual void ResearchByMake(string make, string model, string superTrim, string year, string realTrim, string realTrimUrl, string overlay, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "PRSubmission",
                    "Research",
                    "ByMake"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Research by Make", @__tags);
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("I am on the \"Home\" page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
 testRunner.Then("the \"Home\" page should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 11
 testRunner.When("I click \"Research\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 12
 testRunner.Then("the \"Research\" page should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 14
 testRunner.When("I click \"By Make\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 15
 testRunner.Then("the page should scroll down to the \"Make\" section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 17
 testRunner.When(string.Format("I click on a Make \'{0}\'", make), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 18
 testRunner.Then(string.Format("the Url should change to \'{0}\'", make), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 20
 testRunner.When(string.Format("I click on a Model \'{0}\' \'{1}\'", make, model), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 21
 testRunner.Then(string.Format("the Url should change to \'{0}\'/\'{1}\'/", make, model), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 23
 testRunner.When(string.Format("I click on a Super Trim \'{0}\'", superTrim), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 24
 testRunner.Then(string.Format("the \'{0}\' should be visible", overlay), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 26
 testRunner.When(string.Format("I click on a Real Trim \'{0}\'", realTrim), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 27
 testRunner.Then(string.Format("the Url should change to the following \'{0}\'/\'{1}\'/\'{2}\'/\'{3}\'/", make, model, year, realTrimUrl), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 29
 testRunner.When("I click \"Pricing & Offers\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 30
 testRunner.Then("the side panel should expand", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 32
 testRunner.When("I enter the Zip Code", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 34
 testRunner.When("I click \"Continue to Get Pricing\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 35
 testRunner.Then("the leadform overlay should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 36
 testRunner.Then("the Dealer should be Autobytel Test Toyota", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "id",
                        "value"});
            table1.AddRow(new string[] {
                        "fName",
                        "Bob"});
            table1.AddRow(new string[] {
                        "lName",
                        "Generic"});
            table1.AddRow(new string[] {
                        "strAddr",
                        "18872 MacArthur Blvd"});
            table1.AddRow(new string[] {
                        "HParea",
                        "949"});
            table1.AddRow(new string[] {
                        "HPpre",
                        "225"});
            table1.AddRow(new string[] {
                        "HPphone",
                        "4500"});
            table1.AddRow(new string[] {
                        "email",
                        "testlead@autobytel.com"});
#line 38
 testRunner.When("I Provide Info", ((string)(null)), table1, "When ");
#line 48
 testRunner.When("I click \"Submit and Get Pricing\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 49
 testRunner.Then("the PR Number should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Research by Category")]
        [NUnit.Framework.CategoryAttribute("PRSubmission")]
        [NUnit.Framework.CategoryAttribute("Research")]
        [NUnit.Framework.CategoryAttribute("ByCategory")]
        [NUnit.Framework.TestCaseAttribute("Sedan", "Honda", "Accord", "js-disablesupertrim-accordhybridbase", "2015", "js-trimrow-35764", "hybrid-base", "overlayjs-trimcollection-accordhybridbase", null)]
        [NUnit.Framework.TestCaseAttribute("SUV", "Toyota", "Venza", "js-disablesupertrim-venzaxle", "2015", "js-trimrow-36780", "venza-xle-v6-awd", "overlayjs-trimcollection-venzaxle", null)]
        [NUnit.Framework.TestCaseAttribute("Truck", "Ford", "F-150", "js-disablesupertrim-f150svtraptor", "2014", "js-trimrow-32856", "f-150-svt-raptor-4x4-supercrew-cab-styleside-5-5-box", "overlayjs-trimcollection-f150svtraptor", null)]
        public virtual void ResearchByCategory(string category, string make, string model, string superTrim, string year, string realTrim, string realTrimUrl, string overlay, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "PRSubmission",
                    "Research",
                    "ByCategory"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Research by Category", @__tags);
#line 58
this.ScenarioSetup(scenarioInfo);
#line 59
 testRunner.Given("I am on the \"Home\" page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 60
 testRunner.Then("the \"Home\" page should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 62
 testRunner.When("I click \"Research\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 63
 testRunner.Then("the \"Research\" page should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 65
 testRunner.When("I click \"By Category\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 66
 testRunner.Then("the page should scroll down to the \"Category\" section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 68
 testRunner.When(string.Format("I click on Category \'{0}\'", category), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 69
 testRunner.Then(string.Format("the Url should change to \'{0}\'", category), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 71
 testRunner.When(string.Format("I click on a Super Trim \'{0}\'", superTrim), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 72
 testRunner.Then(string.Format("the \'{0}\' should be visible", overlay), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 74
 testRunner.When(string.Format("I click on a Real Trim \'{0}\'", realTrim), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 75
 testRunner.Then(string.Format("the Url should change to the following \'{0}\'/\'{1}\'/\'{2}\'/\'{3}\'/", make, model, year, realTrimUrl), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 77
 testRunner.When("I click \"Pricing & Offers\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 78
 testRunner.Then("the side panel should expand", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 80
 testRunner.When("I enter the Zip Code", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 82
 testRunner.When("I click \"Continue to Get Pricing\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 83
 testRunner.Then("the leadform overlay should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 84
 testRunner.And("the Dealer should be Autobytel Test Toyota", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "id",
                        "value"});
            table2.AddRow(new string[] {
                        "fName",
                        "Bob"});
            table2.AddRow(new string[] {
                        "lName",
                        "Generic"});
            table2.AddRow(new string[] {
                        "strAddr",
                        "18872 MacArthur Blvd"});
            table2.AddRow(new string[] {
                        "HParea",
                        "949"});
            table2.AddRow(new string[] {
                        "HPpre",
                        "225"});
            table2.AddRow(new string[] {
                        "HPphone",
                        "4500"});
            table2.AddRow(new string[] {
                        "email",
                        "testlead@autobytel.com"});
#line 86
 testRunner.When("I Provide Info", ((string)(null)), table2, "When ");
#line 96
 testRunner.When("I click \"Submit and Get Pricing\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 97
 testRunner.Then("the PR Number should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Cars for Sale by Make")]
        [NUnit.Framework.CategoryAttribute("PRSubmission")]
        [NUnit.Framework.CategoryAttribute("CarsForSale")]
        [NUnit.Framework.TestCaseAttribute("Ford", "Fusion", "zip_overlay_js", null)]
        [NUnit.Framework.TestCaseAttribute("Honda", "Accord", "zip_overlay_js", null)]
        [NUnit.Framework.TestCaseAttribute("Toyota", "Venza", "zip_overlay_js", null)]
        public virtual void CarsForSaleByMake(string make, string model, string overlay, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "PRSubmission",
                    "CarsForSale"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cars for Sale by Make", @__tags);
#line 106
this.ScenarioSetup(scenarioInfo);
#line 107
 testRunner.Given("I am on the \"Home\" page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 108
 testRunner.Then("the \"Home\" page should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 110
 testRunner.When("I click \"Cars for Sale\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 111
 testRunner.Then("the \"Cars for Sale\" page should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 113
 testRunner.When("I click \"By Make\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 114
 testRunner.Then("the page should scroll down to the \"Make\" section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 116
 testRunner.When(string.Format("I click on a Make \'{0}\'", make), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 117
 testRunner.Then(string.Format("the Url should change to \'{0}\'", make), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 119
 testRunner.When(string.Format("I click on a Model \'{0}\' \'{1}\'", make, model), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 120
 testRunner.Then("the \"Results\" page should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 121
 testRunner.And(string.Format("the \'{0}\' should be visible if no zip code is cached", overlay), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "id",
                        "value"});
            table3.AddRow(new string[] {
                        "zip_js",
                        "99999"});
            table3.AddRow(new string[] {
                        "radius_js",
                        "25"});
#line 123
 testRunner.When("I Provide Info", ((string)(null)), table3, "When ");
#line 128
 testRunner.When("I click \"I\'m done, show results\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 131
 testRunner.When("I click on a Vehicle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 134
 testRunner.When("I click \"Pricing & Offers\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 135
 testRunner.Then("the side panel should expand", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 137
 testRunner.When("I click \"Contact the Seller\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 138
 testRunner.Then("the leadform overlay should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "id",
                        "value"});
            table4.AddRow(new string[] {
                        "fName",
                        "Bob"});
            table4.AddRow(new string[] {
                        "lName",
                        "Generic"});
            table4.AddRow(new string[] {
                        "strAddr",
                        "18872 MacArthur Blvd"});
            table4.AddRow(new string[] {
                        "HParea",
                        "949"});
            table4.AddRow(new string[] {
                        "HPpre",
                        "225"});
            table4.AddRow(new string[] {
                        "HPphone",
                        "4500"});
            table4.AddRow(new string[] {
                        "email",
                        "testlead@autobytel.com"});
#line 140
 testRunner.When("I Provide Info", ((string)(null)), table4, "When ");
#line 150
 testRunner.When("I click \"Contact this Dealer\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 151
 testRunner.Then("the PR Number should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Cars for Sale by Category")]
        [NUnit.Framework.CategoryAttribute("PRSubmission")]
        [NUnit.Framework.CategoryAttribute("CarsForSale")]
        [NUnit.Framework.TestCaseAttribute("Sedan", "Ford", "Fusion", "zip_overlay_js", null)]
        [NUnit.Framework.TestCaseAttribute("Sedan", "Honda", "Accord", "zip_overlay_js", null)]
        [NUnit.Framework.TestCaseAttribute("SUV", "Toyota", "Venza", "zip_overlay_js", null)]
        public virtual void CarsForSaleByCategory(string category, string make, string model, string overlay, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "PRSubmission",
                    "CarsForSale"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cars for Sale by Category", @__tags);
#line 160
this.ScenarioSetup(scenarioInfo);
#line 161
 testRunner.Given("I am on the \"Home\" page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 162
 testRunner.Then("the \"Home\" page should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 164
 testRunner.When("I click \"Cars for Sale\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 165
 testRunner.Then("the \"Cars for Sale\" page should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 167
 testRunner.When("I click \"By Category\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 168
 testRunner.Then("the page should scroll down to the \"Category\" section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 170
 testRunner.When(string.Format("I click on Category \'{0}\'", category), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 171
 testRunner.Then("the \"Results\" page should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 172
 testRunner.And(string.Format("the \'{0}\' should be visible if no zip code is cached", overlay), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "id",
                        "value"});
            table5.AddRow(new string[] {
                        "zip_js",
                        "99999"});
            table5.AddRow(new string[] {
                        "radius_js",
                        "25"});
#line 174
 testRunner.When("I Provide Info", ((string)(null)), table5, "When ");
#line 179
 testRunner.When("I click \"I\'m done, show results\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 182
 testRunner.When("I click on a Vehicle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 185
 testRunner.When("I click \"Contact This Seller\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 186
 testRunner.Then("the leadform overlay should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "id",
                        "value"});
            table6.AddRow(new string[] {
                        "fName",
                        "Bob"});
            table6.AddRow(new string[] {
                        "lName",
                        "Generic"});
            table6.AddRow(new string[] {
                        "strAddr",
                        "18872 MacArthur Blvd"});
            table6.AddRow(new string[] {
                        "HParea",
                        "949"});
            table6.AddRow(new string[] {
                        "HPpre",
                        "225"});
            table6.AddRow(new string[] {
                        "HPphone",
                        "4500"});
            table6.AddRow(new string[] {
                        "email",
                        "testlead@autobytel.com"});
#line 188
 testRunner.When("I Provide Info", ((string)(null)), table6, "When ");
#line 198
 testRunner.When("I click \"Contact this Dealer\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 199
 testRunner.Then("the PR Number should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Car Comparisons Choose Car")]
        [NUnit.Framework.CategoryAttribute("Tools")]
        [NUnit.Framework.CategoryAttribute("CarComparisons")]
        public virtual void CarComparisonsChooseCar()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Car Comparisons Choose Car", new string[] {
                        "Tools",
                        "CarComparisons"});
#line 208
this.ScenarioSetup(scenarioInfo);
#line 209
 testRunner.Given("I am on the \"Tools\" page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 210
 testRunner.Then("the \"Tools\" page should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 212
 testRunner.When("I click \"Car Comparisons\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 213
 testRunner.Then("the page should scroll down to the \"Car Comparisons\" section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 215
 testRunner.When("I click \"Begin Your Comparison\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 216
 testRunner.Then("the \"Car Comparison\" page should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 218
 testRunner.When("I click the \"1\" Select a Car button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 219
 testRunner.Then("the Change Car Overlay should be visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "id",
                        "value"});
            table7.AddRow(new string[] {
                        "compareCarMakeSelect",
                        "honda"});
            table7.AddRow(new string[] {
                        "compareCarModelSelect",
                        "accord"});
            table7.AddRow(new string[] {
                        "compareCarTrimSelect",
                        "2015 EX (CVT) Coup"});
#line 221
 testRunner.When("I select a Make/Mode/Trim", ((string)(null)), table7, "When ");
#line 227
 testRunner.When("I click the \"2\" Select a Car button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 228
 testRunner.Then("the Change Car Overlay should be visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "id",
                        "value"});
            table8.AddRow(new string[] {
                        "compareCarMakeSelect",
                        "toyota"});
            table8.AddRow(new string[] {
                        "compareCarModelSelect",
                        "camry"});
            table8.AddRow(new string[] {
                        "compareCarTrimSelect",
                        "2015 LE"});
#line 230
 testRunner.When("I select a Make/Mode/Trim", ((string)(null)), table8, "When ");
#line 236
 testRunner.When("I click the \"Compare\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 237
 testRunner.Then("the \"Car Comparison Results\" page should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Car Comparisons Popular Comparisons")]
        [NUnit.Framework.CategoryAttribute("Tools")]
        [NUnit.Framework.CategoryAttribute("CarComparisons")]
        public virtual void CarComparisonsPopularComparisons()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Car Comparisons Popular Comparisons", new string[] {
                        "Tools",
                        "CarComparisons"});
#line 240
this.ScenarioSetup(scenarioInfo);
#line 241
 testRunner.Given("I am on the \"Tools\" page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 242
 testRunner.Then("the \"Tools\" page should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 244
 testRunner.When("I click \"Car Comparisons\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 245
 testRunner.Then("the page should scroll down to the \"Car Comparisons\" section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 248
 testRunner.When("I click the \"Popular Comparsion One\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 249
 testRunner.Then("the \"Car Comparison Results\" page should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Car Payment Calculators")]
        [NUnit.Framework.CategoryAttribute("Tools")]
        [NUnit.Framework.CategoryAttribute("PaymentCalculators")]
        public virtual void CarPaymentCalculators()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Car Payment Calculators", new string[] {
                        "Tools",
                        "PaymentCalculators"});
#line 252
this.ScenarioSetup(scenarioInfo);
#line 253
 testRunner.Given("I am on the \"Tools\" page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 254
 testRunner.Then("the \"Tools\" page should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 256
 testRunner.When("I click \"Payment Calculators\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 257
 testRunner.Then("the page should scroll down to the \"Car Payment Calculators\" section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 259
 testRunner.When("I click \"Car Payment Calculator\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 260
 testRunner.Then("the \"Car Payment Calculator\" page should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "id",
                        "value"});
            table9.AddRow(new string[] {
                        "PaymentEstimate_purchasePrice",
                        "32000"});
            table9.AddRow(new string[] {
                        "PaymentEstimate_cashRebate",
                        "0"});
            table9.AddRow(new string[] {
                        "PaymentEstimate_tradeIn",
                        "0"});
            table9.AddRow(new string[] {
                        "PaymentEstimate_tradeInOwed",
                        "0"});
            table9.AddRow(new string[] {
                        "PaymentEstimate_downPayment",
                        "3000"});
            table9.AddRow(new string[] {
                        "PaymentEstimate_interestRate",
                        "3"});
            table9.AddRow(new string[] {
                        "PaymentEstimate_termMonths",
                        "48"});
#line 262
 testRunner.When("I Provide Info", ((string)(null)), table9, "When ");
#line 272
 testRunner.When("I click \"Calculate Monthly Payment\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 273
 testRunner.Then("the Payment Estimate should be visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Buying Guides")]
        public virtual void BuyingGuides()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Buying Guides", ((string[])(null)));
#line 275
this.ScenarioSetup(scenarioInfo);
#line 276
 testRunner.Given("I am on the \"Home\" page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 277
 testRunner.Then("the \"Home\" page should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 279
 testRunner.When("I click on the first Car Buying Guide", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 282
 testRunner.When("I click through the article", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 283
 testRunner.Then("I should see the Next Articles page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
