module.exports.car_for_sale=function anonymous(it
/**/) {
var out='';var arr1=it.cars_for_sale;if(arr1){var t,index=-1,l1=arr1.length-1;while(index<l1){t=arr1[index+=1];var img=t.primary_image_url,p=t.price,m=t.mileage,d=t.dealer;out+=' ';if(img!="/assets/svg/no-image-avail.svg"){out+=' <div class="widget-list-item"> <a href="/cars-for-sale/vehicle-details/?q='+( d.id)+'|'+( t.id)+'|'+( it.zipcode)+'|'+( t.make_id)+'|'+( t.model)+'"> <div class="img-container"> <img src="'+( img)+'" alt="" /> <span class="img-label">'+( t.year)+'</span> </div> <div class="desc"> ';if(p.length){out+=' <span class="data primary-data">$'+( p)+'</span> ';}out+=' ';if(m.length){out+=' <span class="data secondary-data">'+( m)+' Miles</span> ';}out+=' <span class="data secondary-data">'+( d.city)+', '+( d.state)+'</span> <span class="data secondary-data">VIN '+( t.vin)+'</span> </div> </a> </div> ';}} } return out;
};module.exports.view_all_btn=function anonymous(it
/**/) {
var out='<button id="c4s_wdg_viewall_btn_js" class="btn-primary">View All</button>';return out;
};module.exports.widget_wrap=function anonymous(it
/**/) {
var out='<h3 class="widget-heading">Cars for Sale</h3><div id="c4s_wdg_zip_notfound_js" class="widget-byline" style="padding:0 6px 6px;border:1px solid #ddd"> <div style="position:relative"> <span id="c4s_wdg_zip_close_btn_js" class="icon" style="height:1em;width:1em;position:absolute;top:4px;right:4px;cursor:pointer"> <svg style="fill:#aaa"> <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/assets/svg/global-sprite.svg#i_close"></use> </svg> </span> </div> <p>Please enter your zipcode to find <b class="c4s_wdg_makemodel_display_js"></b> for sale near you.</p> <form> <input id="c4s_wdg_zip_inp_js" type="text" class="inline-input-box" style="margin-right:4px" placeholder="Enter zip" pattern="[0-9]{5}" size="6" required /> <button class="btn-primary">Find</button> </form></div><div id="c4s_wdg_zip_found_js"> <p class="widget-byline">We found <b class="c4s_wdg_makemodel_display_js"></b> for sale near <a id="c4s_wdg_zip_alter_lnk_js" class="link" href="#"></a> </p> <div id="c4s_wdg_cars_wrap_js"></div> <button id="c4s_wdg_viewall_btn_js" class="btn-primary">View All</button></div>';return out;
};