module.exports.add_change_car_overlay=function anonymous(it
/**/) {
var out='<div id="add_change_car_overlay_js" class="overlay overlay-dk max-450" style="display:none"> <button type="button" class="overlay-close"> <span class="icon"> <svg> <use xlink:href="/assets/svg/global-sprite.svg#i_close"></use> </svg> </span> </button> <div class="dead-middle"> <h1>Select a Car</h1> <section class="add-change-car-container" id="" style="display: block"> <form> <p> <label> <select id="compareCarMakeSelect" class="full"> <option value="">Select a Make</option> ';var arr1=it.makeArr;if(arr1){var makeItem,midx=-1,l1=arr1.length-1;while(midx<l1){makeItem=arr1[midx+=1];out+=' <option value="'+(makeItem.seo_name)+'">'+(makeItem.name)+'</option> ';} } out+=' </select> </label> </p> <p> <label> <select id="compareCarModelSelect" class="full" disabled="disabled"> <option value="">Select a Model</option> </select> </label> </p> <p> <label> <select id="compareCarTrimSelect" class="full" disabled="disabled"> <option value="">Select a Vehicle</option> </select> </label> </p> </form> </section> </div></div>';return out;
};module.exports.compare_data=function anonymous(it
/**/) {
var out=''; var carIndx = 0, carsArr = [], genItemArr = ["name", "invoice", "msrp"], genNameArr = ["Trim", "Invoice Price", "MSRP"], genValArr = [], availCompairArr = [0,1]; for(var carCount=0; carCount<it.carArr.length; carCount++) { carsArr[carCount] = carCount; } { out+=' '; }  for(var genItIndx=0; genItIndx<genItemArr.length; genItIndx++) { genValArr[genItIndx] = []; for(carIndx=0; carIndx<it.carArr.length; carIndx++) { genValArr[genItIndx][carIndx] = []; genValArr[genItIndx][carIndx] = it.carArr[carIndx][genItemArr[genItIndx]]; } { out+=' '; } } { out+=' '; }  var arr1=availCompairArr;if(arr1){var availItem,AIidx=-1,l1=arr1.length-1;while(AIidx<l1){availItem=arr1[AIidx+=1];out+=' ';if(it.carArr.length > AIidx){out+=' <button class="btn-tools left js_delete_compare_car" data-trimid="'+(it.carArr[AIidx].id)+'"> <div style="margin-bottom: 10px; height: 5px; float: right;"><a class="js_delete_compare_car" data-trimid="'+(it.carArr[AIidx].id)+'" style="z-index: 9000;"> <span class="icon i-close"> <svg> <use xlink:href="/assets/svg/global-sprite.svg#i_close"></use> </svg> </span></a></div> ';if(it.carArr[AIidx].images.length > 0){out+=' <picture> <!--[if IE 9]><video style="display: none;"><![endif]--> <source srcset="'+(it.carArr[AIidx].images[0].large)+'" media="(min-width: 1024px)" /> <source srcset="'+(it.carArr[AIidx].images[0].medium)+'" media="(min-width: 640px)" /> <source srcset="'+(it.carArr[AIidx].images[0].small)+'" media="(min-width: 320px)" /> <!--[if IE 9]></video><![endif]--> <img src="'+(it.carArr[AIidx].images[0].small)+'" alt="'+(it.carArr[AIidx].year)+' '+(it.carArr[AIidx].make)+' '+(it.carArr[AIidx].model)+'"> </picture> ';}else if(true){out+=' <img src="/assets/svg/no-image-avail.svg" alt="'+(it.carArr[AIidx].year)+' '+(it.carArr[AIidx].make)+' '+(it.carArr[AIidx].model)+'"> ';}out+=' <h3 class="heading">'+(it.carArr[AIidx].year)+' '+(it.carArr[AIidx].make)+' '+(it.carArr[AIidx].model)+'</h3> </button> ';}else if(true){out+=' <button class="btn-tools left js_add_compare_car"> <span class="icon i-select-car"> <svg  viewbox="0 0 1986 1024"> <use xlink:href="/assets/svg/global-sprite.svg#filter-icon-vehiclecategory-luxurycar"></use> </svg> </span> <h3 class="heading">Select a Car</h3> </button> ';}} } out+='   ';return out;
};module.exports.default_compare_items=function anonymous(it
/**/) {
var out='<button class="btn-tools left js_add_compare_car"> <span class="icon i-select-car"> <svg  viewbox="0 0 1986 1024"> <use xlink:href="/assets/svg/global-sprite.svg#filter-icon-vehiclecategory-luxurycar"></use> </svg> </span> <h3 class="heading">Select a Car</h3></button><button class="btn-tools left js_add_compare_car"> <span class="icon i-select-car"> <svg  viewbox="0 0 1986 1024"> <use xlink:href="/assets/svg/global-sprite.svg#filter-icon-vehiclecategory-luxurycar"></use> </svg> </span> <h3 class="heading">Select a Car</h3></button><!--<button class="btn-tools left js_add_compare_car"> <span class="icon i-select-car"> <svg  viewbox="0 0 1986 1024"> <use xlink:href="/assets/svg/global-sprite.svg#filter-icon-vehiclecategory-luxurycar"></use> </svg> </span> <h3 class="heading">Select a Car</h3></button>-->';return out;
};module.exports.model_select_options=function anonymous(it
/**/) {
var out='<option value="">Select a Model</option>';var arr1=it.modelArr;if(arr1){var modelItem,midx=-1,l1=arr1.length-1;while(midx<l1){modelItem=arr1[midx+=1];out+='<option value="'+(modelItem.seo_name)+'">'+(modelItem.name)+'</option>';} } return out;
};module.exports.trim_select_options=function anonymous(it
/**/) {
var out='<option value="">Select a Vehicle</option>';var arr1=it.trimArr;if(arr1){var trimItem,midx=-1,l1=arr1.length-1;while(midx<l1){trimItem=arr1[midx+=1];out+='<option value="'+(trimItem.id)+'">'+(trimItem.year)+' '+(trimItem.name)+'</option>';} } return out;
};