//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace Car.Com.Domain.LeadEngine {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DropZoneSoap", Namespace="http://www.autobytel.com/")]
    public partial class DropZone : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PingOperationCompleted;
        
        private System.Threading.SendOrPostCallback PingExOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostCommOptFlagOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostCommOptionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback DispositionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ErrorsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DropZone() {
            this.Url = global::Car.Com.Domain.Properties.Settings.Default.Car_Com_Domain_LeadEngine_DropZone;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PingCompletedEventHandler PingCompleted;
        
        /// <remarks/>
        public event PingExCompletedEventHandler PingExCompleted;
        
        /// <remarks/>
        public event PostCompletedEventHandler PostCompleted;
        
        /// <remarks/>
        public event PostCommOptFlagCompletedEventHandler PostCommOptFlagCompleted;
        
        /// <remarks/>
        public event PostCommOptionsCompletedEventHandler PostCommOptionsCompleted;
        
        /// <remarks/>
        public event DispositionCompletedEventHandler DispositionCompleted;
        
        /// <remarks/>
        public event ErrorsCompletedEventHandler ErrorsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.autobytel.com/Ping", RequestNamespace="http://www.autobytel.com/", ResponseNamespace="http://www.autobytel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PingResult Ping(int providerID, int year, string make, string model, string trim, string zipCode) {
            object[] results = this.Invoke("Ping", new object[] {
                        providerID,
                        year,
                        make,
                        model,
                        trim,
                        zipCode});
            return ((PingResult)(results[0]));
        }
        
        /// <remarks/>
        public void PingAsync(int providerID, int year, string make, string model, string trim, string zipCode) {
            this.PingAsync(providerID, year, make, model, trim, zipCode, null);
        }
        
        /// <remarks/>
        public void PingAsync(int providerID, int year, string make, string model, string trim, string zipCode, object userState) {
            if ((this.PingOperationCompleted == null)) {
                this.PingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPingOperationCompleted);
            }
            this.InvokeAsync("Ping", new object[] {
                        providerID,
                        year,
                        make,
                        model,
                        trim,
                        zipCode}, this.PingOperationCompleted, userState);
        }
        
        private void OnPingOperationCompleted(object arg) {
            if ((this.PingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PingCompleted(this, new PingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.autobytel.com/PingEx", RequestNamespace="http://www.autobytel.com/", ResponseNamespace="http://www.autobytel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PingResult PingEx(int providerID, int year, string make, string model, string trim, string zipCode, int ppcSourceGroupID) {
            object[] results = this.Invoke("PingEx", new object[] {
                        providerID,
                        year,
                        make,
                        model,
                        trim,
                        zipCode,
                        ppcSourceGroupID});
            return ((PingResult)(results[0]));
        }
        
        /// <remarks/>
        public void PingExAsync(int providerID, int year, string make, string model, string trim, string zipCode, int ppcSourceGroupID) {
            this.PingExAsync(providerID, year, make, model, trim, zipCode, ppcSourceGroupID, null);
        }
        
        /// <remarks/>
        public void PingExAsync(int providerID, int year, string make, string model, string trim, string zipCode, int ppcSourceGroupID, object userState) {
            if ((this.PingExOperationCompleted == null)) {
                this.PingExOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPingExOperationCompleted);
            }
            this.InvokeAsync("PingEx", new object[] {
                        providerID,
                        year,
                        make,
                        model,
                        trim,
                        zipCode,
                        ppcSourceGroupID}, this.PingExOperationCompleted, userState);
        }
        
        private void OnPingExOperationCompleted(object arg) {
            if ((this.PingExCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PingExCompleted(this, new PingExCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.autobytel.com/Post", RequestNamespace="http://www.autobytel.com/", ResponseNamespace="http://www.autobytel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PostResult Post(Lead lead) {
            object[] results = this.Invoke("Post", new object[] {
                        lead});
            return ((PostResult)(results[0]));
        }
        
        /// <remarks/>
        public void PostAsync(Lead lead) {
            this.PostAsync(lead, null);
        }
        
        /// <remarks/>
        public void PostAsync(Lead lead, object userState) {
            if ((this.PostOperationCompleted == null)) {
                this.PostOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostOperationCompleted);
            }
            this.InvokeAsync("Post", new object[] {
                        lead}, this.PostOperationCompleted, userState);
        }
        
        private void OnPostOperationCompleted(object arg) {
            if ((this.PostCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostCompleted(this, new PostCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.autobytel.com/PostCommOptFlag", RequestNamespace="http://www.autobytel.com/", ResponseNamespace="http://www.autobytel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PostResult PostCommOptFlag(Lead lead, bool optionsFlag) {
            object[] results = this.Invoke("PostCommOptFlag", new object[] {
                        lead,
                        optionsFlag});
            return ((PostResult)(results[0]));
        }
        
        /// <remarks/>
        public void PostCommOptFlagAsync(Lead lead, bool optionsFlag) {
            this.PostCommOptFlagAsync(lead, optionsFlag, null);
        }
        
        /// <remarks/>
        public void PostCommOptFlagAsync(Lead lead, bool optionsFlag, object userState) {
            if ((this.PostCommOptFlagOperationCompleted == null)) {
                this.PostCommOptFlagOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostCommOptFlagOperationCompleted);
            }
            this.InvokeAsync("PostCommOptFlag", new object[] {
                        lead,
                        optionsFlag}, this.PostCommOptFlagOperationCompleted, userState);
        }
        
        private void OnPostCommOptFlagOperationCompleted(object arg) {
            if ((this.PostCommOptFlagCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostCommOptFlagCompleted(this, new PostCommOptFlagCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.autobytel.com/PostCommOptions", RequestNamespace="http://www.autobytel.com/", ResponseNamespace="http://www.autobytel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PostResult PostCommOptions(Lead lead, bool emailOptIn, bool phoneOptIn) {
            object[] results = this.Invoke("PostCommOptions", new object[] {
                        lead,
                        emailOptIn,
                        phoneOptIn});
            return ((PostResult)(results[0]));
        }
        
        /// <remarks/>
        public void PostCommOptionsAsync(Lead lead, bool emailOptIn, bool phoneOptIn) {
            this.PostCommOptionsAsync(lead, emailOptIn, phoneOptIn, null);
        }
        
        /// <remarks/>
        public void PostCommOptionsAsync(Lead lead, bool emailOptIn, bool phoneOptIn, object userState) {
            if ((this.PostCommOptionsOperationCompleted == null)) {
                this.PostCommOptionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostCommOptionsOperationCompleted);
            }
            this.InvokeAsync("PostCommOptions", new object[] {
                        lead,
                        emailOptIn,
                        phoneOptIn}, this.PostCommOptionsOperationCompleted, userState);
        }
        
        private void OnPostCommOptionsOperationCompleted(object arg) {
            if ((this.PostCommOptionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostCommOptionsCompleted(this, new PostCommOptionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.autobytel.com/Disposition", RequestNamespace="http://www.autobytel.com/", ResponseNamespace="http://www.autobytel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DispositionResult Disposition(int providerID, int leadID) {
            object[] results = this.Invoke("Disposition", new object[] {
                        providerID,
                        leadID});
            return ((DispositionResult)(results[0]));
        }
        
        /// <remarks/>
        public void DispositionAsync(int providerID, int leadID) {
            this.DispositionAsync(providerID, leadID, null);
        }
        
        /// <remarks/>
        public void DispositionAsync(int providerID, int leadID, object userState) {
            if ((this.DispositionOperationCompleted == null)) {
                this.DispositionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDispositionOperationCompleted);
            }
            this.InvokeAsync("Disposition", new object[] {
                        providerID,
                        leadID}, this.DispositionOperationCompleted, userState);
        }
        
        private void OnDispositionOperationCompleted(object arg) {
            if ((this.DispositionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DispositionCompleted(this, new DispositionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.autobytel.com/Errors", RequestNamespace="http://www.autobytel.com/", ResponseNamespace="http://www.autobytel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Error[] Errors(int providerID) {
            object[] results = this.Invoke("Errors", new object[] {
                        providerID});
            return ((Error[])(results[0]));
        }
        
        /// <remarks/>
        public void ErrorsAsync(int providerID) {
            this.ErrorsAsync(providerID, null);
        }
        
        /// <remarks/>
        public void ErrorsAsync(int providerID, object userState) {
            if ((this.ErrorsOperationCompleted == null)) {
                this.ErrorsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnErrorsOperationCompleted);
            }
            this.InvokeAsync("Errors", new object[] {
                        providerID}, this.ErrorsOperationCompleted, userState);
        }
        
        private void OnErrorsOperationCompleted(object arg) {
            if ((this.ErrorsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ErrorsCompleted(this, new ErrorsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.autobytel.com/")]
    public partial class PingResult {
        
        private bool coverageField;
        
        private Error[] errorsField;
        
        private Dealer[] dealersField;
        
        private string transactionIDField;
        
        /// <remarks/>
        public bool Coverage {
            get {
                return this.coverageField;
            }
            set {
                this.coverageField = value;
            }
        }
        
        /// <remarks/>
        public Error[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        public Dealer[] Dealers {
            get {
                return this.dealersField;
            }
            set {
                this.dealersField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.autobytel.com/")]
    public partial class Error {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.autobytel.com/")]
    public partial class DispositionResult {
        
        private Disposition statusField;
        
        private string reasonField;
        
        private Error[] errorsField;
        
        /// <remarks/>
        public Disposition Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
        
        /// <remarks/>
        public Error[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.autobytel.com/")]
    public enum Disposition {
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        Pending,
        
        /// <remarks/>
        Accepted,
        
        /// <remarks/>
        Rejected,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.autobytel.com/")]
    public partial class PostResult {
        
        private bool acceptedField;
        
        private string leadIDField;
        
        private Error[] errorsField;
        
        private Dealer[] dealersField;
        
        private string transactionIDField;
        
        /// <remarks/>
        public bool Accepted {
            get {
                return this.acceptedField;
            }
            set {
                this.acceptedField = value;
            }
        }
        
        /// <remarks/>
        public string LeadID {
            get {
                return this.leadIDField;
            }
            set {
                this.leadIDField = value;
            }
        }
        
        /// <remarks/>
        public Error[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        public Dealer[] Dealers {
            get {
                return this.dealersField;
            }
            set {
                this.dealersField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.autobytel.com/")]
    public partial class Dealer {
        
        private string nameField;
        
        private string addressField;
        
        private string cityField;
        
        private string stateField;
        
        private string zipCodeField;
        
        private string phoneField;
        
        private string distanceField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        private int programIDField;
        
        private int dealerIDField;
        
        private string dealerCodeField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }
        
        /// <remarks/>
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public int ProgramID {
            get {
                return this.programIDField;
            }
            set {
                this.programIDField = value;
            }
        }
        
        /// <remarks/>
        public int DealerID {
            get {
                return this.dealerIDField;
            }
            set {
                this.dealerIDField = value;
            }
        }
        
        /// <remarks/>
        public string DealerCode {
            get {
                return this.dealerCodeField;
            }
            set {
                this.dealerCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.autobytel.com/")]
    public partial class Provider {
        
        private int providerIDField;
        
        private string nameField;
        
        private string serviceField;
        
        /// <remarks/>
        public int ProviderID {
            get {
                return this.providerIDField;
            }
            set {
                this.providerIDField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.autobytel.com/")]
    public partial class Customer {
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityField;
        
        private string stateField;
        
        private string zipCodeField;
        
        private string homePhoneField;
        
        private string workPhoneField;
        
        private string faxPhoneField;
        
        private string emailAddressField;
        
        private ContactMethod bestContactMethodField;
        
        private ContactTime bestContactTimeField;
        
        private TimeFrame purchaseTimeFrameField;
        
        private string commentsField;
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        public string HomePhone {
            get {
                return this.homePhoneField;
            }
            set {
                this.homePhoneField = value;
            }
        }
        
        /// <remarks/>
        public string WorkPhone {
            get {
                return this.workPhoneField;
            }
            set {
                this.workPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string FaxPhone {
            get {
                return this.faxPhoneField;
            }
            set {
                this.faxPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        public ContactMethod BestContactMethod {
            get {
                return this.bestContactMethodField;
            }
            set {
                this.bestContactMethodField = value;
            }
        }
        
        /// <remarks/>
        public ContactTime BestContactTime {
            get {
                return this.bestContactTimeField;
            }
            set {
                this.bestContactTimeField = value;
            }
        }
        
        /// <remarks/>
        public TimeFrame PurchaseTimeFrame {
            get {
                return this.purchaseTimeFrameField;
            }
            set {
                this.purchaseTimeFrameField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.autobytel.com/")]
    public enum ContactMethod {
        
        /// <remarks/>
        HomePhone,
        
        /// <remarks/>
        WorkPhone,
        
        /// <remarks/>
        FaxPhone,
        
        /// <remarks/>
        Email,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.autobytel.com/")]
    public enum ContactTime {
        
        /// <remarks/>
        Morning,
        
        /// <remarks/>
        Afternoon,
        
        /// <remarks/>
        Evening,
        
        /// <remarks/>
        NoPreference,
        
        /// <remarks/>
        Day,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.autobytel.com/")]
    public enum TimeFrame {
        
        /// <remarks/>
        Within48Hours,
        
        /// <remarks/>
        Within14Days,
        
        /// <remarks/>
        Within30Days,
        
        /// <remarks/>
        Over30Days,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.autobytel.com/")]
    public partial class Tradein {
        
        private int yearField;
        
        private string makeField;
        
        private string modelField;
        
        private string trimField;
        
        private int odometerField;
        
        /// <remarks/>
        public int Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        public string Make {
            get {
                return this.makeField;
            }
            set {
                this.makeField = value;
            }
        }
        
        /// <remarks/>
        public string Model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        public string Trim {
            get {
                return this.trimField;
            }
            set {
                this.trimField = value;
            }
        }
        
        /// <remarks/>
        public int Odometer {
            get {
                return this.odometerField;
            }
            set {
                this.odometerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.autobytel.com/")]
    public partial class Vehicle {
        
        private VehicleStatus statusField;
        
        private string vehicleIDField;
        
        private int yearField;
        
        private string makeField;
        
        private string modelField;
        
        private string trimField;
        
        private string interiorColorField;
        
        private string exteriorColorField;
        
        private string[] optionsField;
        
        private FinanceMethod preferedFinanceMethodField;
        
        private int downPaymentField;
        
        private string commentsField;
        
        private string imageTagField;
        
        /// <remarks/>
        public VehicleStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string VehicleID {
            get {
                return this.vehicleIDField;
            }
            set {
                this.vehicleIDField = value;
            }
        }
        
        /// <remarks/>
        public int Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        public string Make {
            get {
                return this.makeField;
            }
            set {
                this.makeField = value;
            }
        }
        
        /// <remarks/>
        public string Model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        public string Trim {
            get {
                return this.trimField;
            }
            set {
                this.trimField = value;
            }
        }
        
        /// <remarks/>
        public string InteriorColor {
            get {
                return this.interiorColorField;
            }
            set {
                this.interiorColorField = value;
            }
        }
        
        /// <remarks/>
        public string ExteriorColor {
            get {
                return this.exteriorColorField;
            }
            set {
                this.exteriorColorField = value;
            }
        }
        
        /// <remarks/>
        public string[] Options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
            }
        }
        
        /// <remarks/>
        public FinanceMethod PreferedFinanceMethod {
            get {
                return this.preferedFinanceMethodField;
            }
            set {
                this.preferedFinanceMethodField = value;
            }
        }
        
        /// <remarks/>
        public int DownPayment {
            get {
                return this.downPaymentField;
            }
            set {
                this.downPaymentField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        public string ImageTag {
            get {
                return this.imageTagField;
            }
            set {
                this.imageTagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.autobytel.com/")]
    public enum VehicleStatus {
        
        /// <remarks/>
        New,
        
        /// <remarks/>
        Used,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.autobytel.com/")]
    public enum FinanceMethod {
        
        /// <remarks/>
        Cash,
        
        /// <remarks/>
        Finance,
        
        /// <remarks/>
        Lease,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.autobytel.com/")]
    public partial class Lead {
        
        private string prospectIDField;
        
        private System.DateTime requestDateField;
        
        private Vehicle vehicleField;
        
        private Tradein tradeinField;
        
        private Customer customerField;
        
        private Dealer[] dealersField;
        
        private Provider providerField;
        
        /// <remarks/>
        public string ProspectID {
            get {
                return this.prospectIDField;
            }
            set {
                this.prospectIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RequestDate {
            get {
                return this.requestDateField;
            }
            set {
                this.requestDateField = value;
            }
        }
        
        /// <remarks/>
        public Vehicle Vehicle {
            get {
                return this.vehicleField;
            }
            set {
                this.vehicleField = value;
            }
        }
        
        /// <remarks/>
        public Tradein Tradein {
            get {
                return this.tradeinField;
            }
            set {
                this.tradeinField = value;
            }
        }
        
        /// <remarks/>
        public Customer Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        public Dealer[] Dealers {
            get {
                return this.dealersField;
            }
            set {
                this.dealersField = value;
            }
        }
        
        /// <remarks/>
        public Provider Provider {
            get {
                return this.providerField;
            }
            set {
                this.providerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void PingCompletedEventHandler(object sender, PingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PingResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PingResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void PingExCompletedEventHandler(object sender, PingExCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PingExCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PingExCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PingResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PingResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void PostCompletedEventHandler(object sender, PostCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PostResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PostResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void PostCommOptFlagCompletedEventHandler(object sender, PostCommOptFlagCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostCommOptFlagCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostCommOptFlagCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PostResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PostResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void PostCommOptionsCompletedEventHandler(object sender, PostCommOptionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostCommOptionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostCommOptionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PostResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PostResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DispositionCompletedEventHandler(object sender, DispositionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DispositionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DispositionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DispositionResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DispositionResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ErrorsCompletedEventHandler(object sender, ErrorsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ErrorsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ErrorsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Error[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Error[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591